name: Synchronize Helm Chart content from OCP docs.

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3
        with:
          repository: openshift/openshift-docs
          p
          ref: enterprise-4.11

      - name: config docs-bot
        run: |
          git config --global user.email "docs-bot@redhat.com"
          git config --global user.name "docs-bot"

      - name: clone mw-shared-modules
        uses: actions/checkout@v3
        with:
          repository: inoxx03/mw-shared-modules
          ref: master
          path: runtimes-common
          ssh-key: ${{ secrets.DOCS_BOT_KEY }}

      - name: wipe helm-charts
        run: |
          cd helm-charts
          rm -rf helm-charts

      - name: rsync rst files
        run: |
          rsync -vr --delete --relative \
            --exclude='**/*.html' \
            --exclude='**/*.css' \
            --exclude='**/*.js' \
            --exclude='**/*.json' \
            --exclude='**/*.yaml' \
            --exclude='**/*.yml' \
            --exclude='**/*.xml' \
            --exclude='**/*.png' \
            --exclude='**/*.svg' \
            --exclude='**/*.ttf' \
            --exclude='**/*.woff' \
            --exclude='**/*.py' \
            --exclude='**/*.eot' \
            --exclude='**/*.po' \
            --exclude='**/*.ico' \
            --exclude='**/*.map' \
            --exclude='**/*.txt' \
            --exclude='**/*.conf' \
            --exclude='**/Makefile' \
            --exclude='_*/*' \
            --exclude='**/_*/*' \
            --exclude='**/locale/*' \
            --exclude='userguide/*' \
            --exclude='release-notes/*' \
            --exclude='contrib/*' \
            ./product-docs/**/ \
            sync
          rm -rf product-docs

      - name: commit files
        run: |
          git add . --all
          git diff-index --quiet HEAD || git commit -m "[TEST] Synchronize Helm Chart content form OpenShift docs"

      - name: push changes
        uses: ad-m/github-push-action@master
        with:
          directory: sync
          github_token: ${{ secrets.DOCS_BOT_PAT }}
          branch: main
